//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ca.Skoolbo.Homesite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Assets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ca.Skoolbo.Homesite.Resources.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://skoolbo-assets.s3.amazonaws.com/avatars/{0}.png.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://skoolbo-assets.s3.amazonaws.com/avatars_128/{0}.png.
        /// </summary>
        public static string Avatar128 {
            get {
                return ResourceManager.GetString("Avatar128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://skoolbo-assets.s3.amazonaws.com/avatars_128_no_background/{0}.png.
        /// </summary>
        public static string Avatar128NoBackground {
            get {
                return ResourceManager.GetString("Avatar128NoBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://skoolbo-assets.s3.amazonaws.com/avatars_256_no_background/{0}.png.
        /// </summary>
        public static string Avatar256NoBackground {
            get {
                return ResourceManager.GetString("Avatar256NoBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://skoolbowebcore.s3.amazonaws.com/img/avatar/female/0.png.
        /// </summary>
        public static string AvatarFemaleDefault {
            get {
                return ResourceManager.GetString("AvatarFemaleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://skoolbowebcore.s3.amazonaws.com/img/avatar/male/0.png.
        /// </summary>
        public static string AvatarMaleDefault {
            get {
                return ResourceManager.GetString("AvatarMaleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://skoolbowebcore.s3.amazonaws.com/img/categories/{0}.png.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://skoolbowebcore.s3.amazonaws.com/img/{0}/{1}.png.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://skoolbowebcore.s3.amazonaws.com/img/states/{0}/{1}.png.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://skoolbowebcore.s3.amazonaws.com/img/states/{0}/SIN.png.
        /// </summary>
        public static string StateDefault {
            get {
                return ResourceManager.GetString("StateDefault", resourceCulture);
            }
        }
    }
}
