//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ca.Skoolbo.Homesite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceDisplay {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDisplay() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ca.Skoolbo.Homesite.Resources.ResourceDisplay", typeof(ResourceDisplay).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        public static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Improvement.
        /// </summary>
        public static string CountryAvgImprovement {
            get {
                return ResourceManager.GetString("CountryAvgImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string CountryClassesTab {
            get {
                return ResourceManager.GetString("CountryClassesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Million Club.
        /// </summary>
        public static string CountryMillionClub {
            get {
                return ResourceManager.GetString("CountryMillionClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Best.
        /// </summary>
        public static string CountryPersonalBest {
            get {
                return ResourceManager.GetString("CountryPersonalBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Best.
        /// </summary>
        public static string CountryPersonalBestTab {
            get {
                return ResourceManager.GetString("CountryPersonalBestTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        public static string CountrySchool {
            get {
                return ResourceManager.GetString("CountrySchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        public static string CountrySchoolsTab {
            get {
                return ResourceManager.GetString("CountrySchoolsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string CountryStudentsTab {
            get {
                return ResourceManager.GetString("CountryStudentsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Champs.
        /// </summary>
        public static string CountrySuperChamps {
            get {
                return ResourceManager.GetString("CountrySuperChamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string CountryWorldTab {
            get {
                return ResourceManager.GetString("CountryWorldTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Improvement.
        /// </summary>
        public static string GlobalAvgImprovement {
            get {
                return ResourceManager.GetString("GlobalAvgImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string GlobalClassesTab {
            get {
                return ResourceManager.GetString("GlobalClassesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Million Club.
        /// </summary>
        public static string GlobalMillionClub {
            get {
                return ResourceManager.GetString("GlobalMillionClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Best.
        /// </summary>
        public static string GlobalPersonalBest {
            get {
                return ResourceManager.GetString("GlobalPersonalBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Best.
        /// </summary>
        public static string GlobalPersonalBestTab {
            get {
                return ResourceManager.GetString("GlobalPersonalBestTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        public static string GlobalSchool {
            get {
                return ResourceManager.GetString("GlobalSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        public static string GlobalSchoolsTab {
            get {
                return ResourceManager.GetString("GlobalSchoolsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string GlobalStudentsTab {
            get {
                return ResourceManager.GetString("GlobalStudentsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Champs.
        /// </summary>
        public static string GlobalSuperChamps {
            get {
                return ResourceManager.GetString("GlobalSuperChamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string GlobalWorldTab {
            get {
                return ResourceManager.GetString("GlobalWorldTab", resourceCulture);
            }
        }
    }
}
